function createfigure(function1, function2, function3, X1, Y1)
%CREATEFIGURE(function1, function2, function3, X1, Y1)
%  FUNCTION1:  function f(x)
%  FUNCTION2:  function f(x)
%  FUNCTION3:  function f(x)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 13-Sep-2018 09:06:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.27843949044586 0.823554817275748]);
hold(axes1,'on');

% Create fplot
fplot(function1,[0 5],'DisplayName','Average Cost  {Q}^{2} - {5Q} + {60}',...
    'Parent',axes1,...
    'Color',[0 0 1]);

% Create fplot
fplot(function2,[0 5],...
    'DisplayName','Total Cost {60} {Q} - {5} {Q}^{2} + {Q}^{3}',...
    'Parent',axes1,...
    'Color',[0 1 0]);

% Create fplot
fplot(function3,[0 5],'DisplayName','Marginal Cost {60} - {10Q} + {3Q}^{2}',...
    'Parent',axes1,...
    'Color',[0 0 0]);

% Create plot
plot(X1,Y1,'DisplayName','ACmin | ( 2.5 , 53.75 )','Marker','o',...
    'LineStyle','none',...
    'Color',[1 0 0]);

% Create title
title('Optimization Graph');

box(axes1,'on');
axis(axes1,'tight');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.141438428874735 0.657937430786268 0.130175159235669 0.18936877076412]);

